name : pcs-chrono
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - beautifulsoup4
  - pandas
  - requests
  - numpy
  - sqlite
  - matplotlib
  - jupyterlab
  - ipykernel
  - notebook
  - seaborn
  - scikit-learn
  - tqdm
  - pytest
  - pylint
  - aiohttp